# Site settings
title: Morgan E. Winkler
email: mewinkl@g.clemson.edu
description: > # this means to ignore newlines until "baseurl:"
  I’m a recent Clemson graduate pursuing a career in academia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mewinkl.github.io” # the base hostname & protocol for your site
github_username:  mewinkl

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""